services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitter_dev
    volumes:
      - /var/lib/postgresql/twitter_data
    ports:
      - "5432:5432"
